
export const ONBOARDING = {
	LOAD_SLIDER: 'PROFILE_SUCCESS'
}

export const PROFILE = {
	SET_FB_USER: 'PROFILE_SET_FB_USER',
	LOGOUT: 'PROFILE_LOGOUT',
	SET_FB_TOKEN: 'PROFILE_SET_FB_TOKEN',
	SET_PROFILE: 'PROFILE_SET_PROFILE',
	SET_MY_POSTS: 'PROFILE_SET_MY_POSTS',
	SET_REGISTERING: 'PROFILE_SET_REGISTERING'
}